### ISSUE TITLE
[Feature] Check chdman version before converting ROMs

### ISSUE THREAD

**Issue by TheRealGusBus** [alucryd/oxyromon#106]
Older versions of chdman don't generate playable Dreamcast files: <https://github.com/mamedev/mame/issues/6466>

I'm wondering if it's sensible/practical to add a version check to ensure chdman isn't going to generate junk CHDs for the platform. Thoughts?

**Comment by alucryd** [comment]
Prompting with a warning doesn't sound like a bad idea. I'm also thinking of adding a new `info` subcommand which would print some statistics and system info, including external tools.

**Comment by TheRealGusBus** [comment]
Well, bad news. Upon verifying a nearly full Dreamcast set, most of the CHDs went into the trash. The only ones that didn't were mostly unlicensed games or MIL-CDs (which I believe is the format that unlicensed games need to use). 

I'll try to dig for more information on why this happened.

**Comment by alucryd** [comment]
Hmm, so the files can't even be reversed? That's bad, I don't think a warning is enough, might just ban older versions altogether. I see 0.236 being mentioned in the thread, is that a good minimum version? It seems to have problems still according to one comment.

**Comment by TheRealGusBus** [comment]
To clarify, older versions produce an unplayable CHD file (at least for some emulators).

Newer versions produce playable CHD files but won't verify with `oxyromon check-roms`.  I'm guessing oxyromon, after extracting the CHD for verification, then splits the bin file into separate tracks? If so, the Redump Dreamcast dumps likely require special handling in that area.

Here's a relevant discussion on implementing proper cues for the Redump Dreamcast dumps:
<http://forum.redump.org/topic/19969/sega-dreamcast-multicue-gdi/>

**Comment by TheRealGusBus** [comment]
Here's an example of chdman info output, the original Redump cues, and the cues generated by chdman extractcd:

chdman info:
```
chdman - MAME Compressed Hunks of Data (CHD) manager 0.260 (unknown)
Input file:   WWF Royal Rumble (USA).chd
File Version: 5
Logical size: 1,344,324,096 bytes
Hunk Size:    19,584 bytes
Total Hunks:  68,644
Unit Size:    2,448 bytes
Total Units:  549,152
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     147,347,006 bytes
Ratio:        11.0%
SHA1:         fc48213dc353171f2e43141ddc73850e4acd08d7
Data SHA1:    0c3184066af2191231fd8514d3cd62931a073ee4
Metadata:     Tag='CHGD'  Index=0  Length=98 bytes
              TRACK:1 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:600 PAD:150 PREGA
Metadata:     Tag='CHGD'  Index=1  Length=98 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:44400 PAD:43874 PREGA
Metadata:     Tag='CHGD'  Index=2  Length=99 bytes
              TRACK:3 TYPE:MODE1_RAW SUBTYPE:NONE FRAMES:504150 PAD:0 PREG
```

Redump cue:
```
REM SINGLE-DENSITY AREA
FILE "WWF Royal Rumble (USA) (Track 1).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "WWF Royal Rumble (USA) (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
REM HIGH-DENSITY AREA
FILE "WWF Royal Rumble (USA) (Track 3).bin" BINARY
  TRACK 03 MODE1/2352
    INDEX 01 00:00:00
```

cue from chdman extractcd:
```
FILE "wwf" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    INDEX 01 00:08:00
  TRACK 03 MODE1/2352
    INDEX 01 10:00:00
```

**Comment by alucryd** [comment]
I may be missing something, but verifying Dreamcast CHDs works fine here (maybe I only have games that play nice with chdman). oxyromon splits the CHD according to the Redump CUE, the CUE file generated by chdman is in most cases garbage, I never use it.

**Comment by TheRealGusBus** [comment]
The only ones that verified for me were unlicensed games. Which chdman version are you using? I'm on 0.260.

This is the current commit I'm on with oxyromon:

```
commit bb3bbae6cd326c25def0386f26ad1778c3a17665 (HEAD -> master, tag: 0.17.0, origin/master, origin/HEAD)
Author: Maxime Gauduin <alucryd@archlinux.org>
Date:   Thu Nov 2 21:33:08 2023 +0100

    chore: update sqlx offline data
```

**Comment by alucryd** [comment]
I'm on 0.261, latest develop commit, but develop only has a few technical migrations compared to master, CHD handling hasn't changed for a while.

**Comment by alucryd** [comment]
https://github.com/alucryd/oxyromon/commit/62d539dd3089dad309469dda6f384d9ca699c28d adds an info subcommand and aborts Dreamcast CHD conversions if chdman isn't at least 0.240 to be safe. It's a 2 year old release and should be fairly easy to get installed on any system.
