### ISSUE TITLE
[Feature] Verify roms immediately after conversion before deleting original files

### ISSUE THREAD

**Issue by TheRealGusBus** [alucryd/oxyromon#111]
Add a command line option to verify each ROM file immediately after conversion to ensure it's in fact reversible. This prevents the loss of the original media when converting to the various different formats if a certain version of said format's tool has bugs.

**Comment by alucryd** [comment]
It's been on my to-do for ages, sure, I can prioritize this. I procrastinated for so long because I will need to factorize a lot of code to avoid duplication. Then again, the new `export-roms` command also needs a lot of factorization, oh well.

**Comment by alucryd** [comment]
Big refacto is done, I'll be implementing that tomorrow most likely.

**Comment by alucryd** [comment]
Done in https://github.com/alucryd/oxyromon/commit/e5ff80bb62f33e3ed40e5b419ec32f4f9420322c :)
