### ISSUE TITLE
[Feature] Add a foreign (`-f`) option to `purge-roms`

### ISSUE THREAD

**Issue by TylerVigario** [alucryd/oxyromon#112]
Would be nice if we could check (and optionally delete) foreign ROMs within managed folders.

**EDIT  1/15/24**: If this is the meaning of orphan, then for whatever reason, I found it keeping extra `bin` files even though I have a `CHD` for the game. I could imagine normal files (`.bin`, etc) might not be considered _"orphan"_ if we do not check for the existence of another format (i.e. `7z`, `zip`, `CHD`, `ISO`, etc)

**Comment by alucryd** [comment]
Added in https://github.com/alucryd/oxyromon/commit/76ab5c2b8fd635c996384d5da6720efa1a45f485

Unlike the other flags, this one will prompt you for every foreign file found, as you might want to keep some of them, like translation patches.

**Comment by TylerVigario** [comment]
@alucryd I Just tested it, and it works great! I agree that each deletion should be explicit.
