### ISSUE TITLE
[Feature] Import No-Intro DAT ZIP

### ISSUE THREAD

**Issue by maxexcloo** [alucryd/oxyromon#115]
I'd like to be able to import the downloaded No-Intro ZIP file directly rather than extracting and importing one by one - it might be possible to read every DAT inside a ZIP and import?

**Comment by alucryd** [comment]
Added support for zip files in https://github.com/alucryd/oxyromon/commit/dd248143645a16bdae65ab5f7c4857dc16fb74d8.
