### ISSUE TITLE
[Feature] Handle Sony PlayStation PBP Images

### ISSUE THREAD

**Issue by maxexcloo** [alucryd/oxyromon#119]
While importing my PSX collection I noticed that PBP images don't seem to be handled - I'm not sure if these can be converted in a similar way to CHD files but it might be an idea.

https://i12bretro.github.io/tutorials/0323.html

https://github.com/RupertAvery/PSXPackager

**Comment by alucryd** [comment]
According to [this](https://emulation.gametechwiki.com/index.php/Save_disk_space_for_ISOs#PBP_.28PSP_Format_for_PS1_Images.29), PBP is not a fully reversible format, as such it won't be possible to recreate the original cue/bin to check against the database.
I will probably support exporting to it though, when I finally start working on a `export-roms` command.

**Comment by maxexcloo** [comment]
Fair enough - thought that could be the case! What’s the use case for export roms? Currently I have a pretty convoluted bash script that takes a mapping csv and exports my rom folders to different system names for use with my handhelds - is it something like that?

**Comment by alucryd** [comment]
Exactly that, and more :) The personal use case I had in mind was to be able to export to my various Everdrives, or to various consoles internal drives via ftp for instance. That will include a bunch of filters and renaming options down the road.
