### ISSUE TITLE
[Feature] Config setting for Database Path

### ISSUE THREAD

**Issue by etherwrangler** [alucryd/oxyromon#123]
Would it be possible to add a config setting for either ```DATABASE_PATH``` or ```DATA_DIR```?  My use case with this is to change the SQLite db from the existing location of ```${data_dir}/oxyromon``` to the folder on my NAS where I have the EXE for oxyromon copied.

This folder also has the external programs such as 7z etc allowing me to run oxyromon from my desktop or a VM that is always on my NAS to manage the ROM library.  Neither would access the database at the same time so in this use case I would not be worried about corruption.

**Comment by etherwrangler** [comment]
Not sure what I was thinking yesterday but after thinking on this for a day this would work better in a container than what I'm trying to do.

**Comment by alucryd** [comment]
Actually this is already possible via the `OXYROMON_DATA_DIRECTORY` env variable, but looks like you thought of an alternative already :)
