### ISSUE TITLE
Bulk conversion failing, attempting to convert already converted game

### ISSUE THREAD

**Issue by monyarm** [alucryd/oxyromon#139]
```
❯ oxyromon convert-roms -f CHD -d -s "Sony - PlayStation"
Processing "Sony - PlayStation"
Creating "Incredible Hulk, The - The Pantheon Saga (USA).chd"
Error: SimpleError { err: "Error parsing input file (/mnt/Games/Sony - PlayStation/Incredible Hulk, The - The Pantheon Saga (USA).cue: No such file or directory)\n\nFatal error occurred: 1\n" }
```
Incredible Hulk, The - The Pantheon Saga (USA).cue and Incredible Hulk, The - The Pantheon Saga (USA).chd exist, no other files relating to the game exist. Both files are imported. And yet when I try to convert all PS1 games, it tries converting the game, and creating a chd. Then it fails. My best guess is that it might believe the .bin to still be imported, and the "No such file" is regarding the .bin files referenced in the cue, and not the cue itself.
I'm on the latest commit of develop.

**Comment by alucryd** [comment]
That's odd indeed, sth must have gone wrong when doing the initial rom conversion. Does `purge-roms -m` find any missing file? If so your theory is correct, and you should be able to import the CHD after the purge.

**Comment by alucryd** [comment]
CUE files are no longer auto imported with recent chdman 0.265+, and need to be explicitly imported into oxyromon 0.20.0, so it's not possible to run into this anymore.
