### ISSUE TITLE
Debian 12 uses 7zz

### ISSUE THREAD

**Issue by anderbubble** [alucryd/oxyromon#143]
Debian 12 uses 7zz, rather than 7z, in its 7zip package.

I see this was updated for macOS at #105, but I think a more general-purpose "try 7zz, fall back to 7z" would be good.

**Comment by alucryd** [comment]
Ah, thanks for the heads up. Sounds good to me, will do that during the week.

**Comment by alucryd** [comment]
Implemented in https://github.com/alucryd/oxyromon/commit/8a22fe76e1948b48c84c7ba50246998972767e18

**Comment by anderbubble** [comment]
Thanks!
