### ISSUE TITLE
[Request] "CHD_COMPRESSION_ALGORITHM" - Choose order on the list

### ISSUE THREAD

**Issue by Immersion95** [alucryd/oxyromon#149]
Would it be possible to choose the order for the CHD CD/DVD algorithms ?

At the moment Oxyromon uses the alphabetical order if there are multiple algos, chdman info will find the order that was used on Oxyromon so the order has significance.

Ex : For "CHD_CD_COMPRESSION_ALGORITHM"

- **cdzs,cdzl,cdfl** ----> What I want
- **cdfl,cdzl,cdzs** ----> What Oxyromon will use

**Comment by alucryd** [comment]
Sure thing, will have a look during the week.

**Comment by alucryd** [comment]
Added in https://github.com/alucryd/oxyromon/commit/3e6e66fffa59d0f60509da66ed299a832e065d08 :) oxyromon will not sort CHD algorithms anymore, they will be passed in the same order they were added in the database (you will need to play with `-r` and `-a` to reorder them).

**Comment by Immersion95** [comment]
> Added in [3e6e66f](https://github.com/alucryd/oxyromon/commit/3e6e66fffa59d0f60509da66ed299a832e065d08) :) oxyromon will not sort CHD algorithms anymore, they will be passed in the same order they were added in the database (you will need to play with `-r` and `-a` to reorder them).

That's perfect ! Thx a lot !
