### ISSUE TITLE
[Request] Add building instructions for Windows

### ISSUE THREAD

**Issue by Immersion95** [alucryd/oxyromon#151]
Rust can't build asm-hashes with MSVC at the moment --->[See here](https://github.com/RustCrypto/asm-hashes/issues/17)

It has to be built with GNU, is it possible to add this command in the build instructions :

- cargo build --release --target x86_64-pc-windows-gnu

Of course you have to add MSYS2-mingw-w64 to the variable PATH to use gcc.exe

**Comment by alucryd** [comment]
Thanks for the heads up. I have no Windows machine so my only option is GNU and I didn't catch that one. I'll add build instructions, an alternative would be to disable the `enable-asm` feature when building with MSVC, you won't see any difference if you use CRC as your default hash, as `asm-hashes` is only used with MD5 and SHA1.

**Comment by Immersion95** [comment]
> Thanks for the heads up. I have no Windows machine so my only option is GNU and I didn't catch that one. I'll add build instructions, an alternative would be to disable the `enable-asm` feature when building with MSVC, you won't see any difference if you use CRC as your default hash, as `asm-hashes` is only used with MD5 and SHA1.

Yes it works without it too :)

- cargo build --release --no-default-features --features use-rustls
