### ISSUE TITLE
Unable to purge system if roms deleted from filesystem

### ISSUE THREAD

**Issue by weejames** [alucryd/oxyromon#153]
Manually deleted some roms for a system from the filesystem and tried to purge the system from the database using `oxymoron purge-systems`.

After selecting the relevant system from the menu it fails due to being unable to find the roms for the system. Would expect the command to remove all data from the oxyromon database for the system regardless of the presence of the actual files.

Example output, details omitted.

```
...
Error: SimpleError { err: "Failed to copy \"path_here\filename_here" to \"path_here/Trash/filename_here\", No such file or directory (os error 2)" }
...
```

**Comment by aarongeorge** [comment]
Try `oxyromon purge-roms -m` and then `oxyromon purge-systems`

**Comment by weejames** [comment]
Perfect. Thanks for the help.
