### ISSUE TITLE
Problem importing RVZ

### ISSUE THREAD

**Issue by ColetteDiskette** [alucryd/oxyromon#156]
EDIT: Ah, I got it. Needed to install `dolphin-emu-tool` from the Arch `extra` repo. This is solved for me. Perhaps the error message could somehow be clearer? Either way, things are working for me now!

Original post:
I'm on Arch Linux and have Dolphin installed via Arch's `extra` repo. The binary is called `dolphin-emu`. However, when I try to `oxyromon import-roms *.rvz` in a folder with one RVZ, I get the output:

```
Processing "4x4 Evo 2 (USA).rvz"
Please install dolphin
```

I'm assuming oxyromon isn't finding my Dolphin install? Perhaps because of the binary name? Thanks in advance.

**Comment by alucryd** [comment]
Ah yes, I'll change `dolphin` to `dolphin-tool`, it's a separate binary. Most distros ship it alongside dolphin, but on arch it's a split package indeed.

**Comment by alucryd** [comment]
Fixed in 941b5df5af68502a3d280522c5db8bb2aebdd4b6 :)
