### ISSUE TITLE
[Bug/Feature?] Moving ROM_DIRECTORY

### ISSUE THREAD

**Issue by vickyorlo** [alucryd/oxyromon#166]
While setting up oxyromon, I had a slightly unusual situation that required me to create a rom directory in one location, import all my stuff, and then move it later. I had thought changing the ROM_DIRECTORY configuration parameter would be enough for oxyromon to start looking for files in the right folder, but sadly, no such luck. A lot of commands now fail with a "Failed to get canonicalized path" error looking in the old location. A quick browse of the internal database tells me that oxyromon indeed stores full paths to managed files.
Is there some way to point the references to the right locations? If not, perhaps this could be considered a bug or a missing feature. It makes more sense for the program to always look for files in ROM_DIRECTORY, but stability/performance concerns might dictate otherwise. A migrate command (with the option to move the files from the old location to the new or to not do that and let the user do it themselves) might be useful.
Another workaround of course would be an SQL query to manually fix these broken paths but I'll be honest, I don't really want to do that.

**Comment by alucryd** [comment]
I had pondered this a while ago, and had decided that when the time would come that this would be requested, I would store relative paths in the database instead of absolute ones. That way, the ROM directory can be manually moved, and `ROM_DIRECTORY` updated to reflect the changes. This will make the whole installation portable. How does that sound?

**Comment by vickyorlo** [comment]
To me, that is probably the most sensible option. Perhaps a message to double-check your ROM_DIRECTORY setting when oxyromon encounters a missing file could be helpful as well?

**Comment by alucryd** [comment]
Implemented in https://github.com/alucryd/oxyromon/commit/5cc1d92da9b9d6b2304fe89d278409b08adfbadd
This was a much bigger rewrite than I anticipated, essentially took me all weekend. Hopefully I haven't introduced any major bug with this one. Please let me know how it goes if you're able to test.

**Comment by vickyorlo** [comment]
I'll be honest - I expected this to take weeks instead of two days. I'll test at my earliest convenience.

**Comment by alucryd** [comment]
@vickyorlo What `ROM_DIRECTORY` value did you have when you first started oxyromon after the update?

I should have mentioned this, apologies. oxyromon runs database migrations at startup, the new version will automatically strip the current `ROM_DIRECTORY` prefix from all saved paths, and do it only once. It should be fine for most people with a regular setup, but if you had already changed `ROM_DIRECTORY` to your new path prior to launching the new version, then the database migration must have left every path as is.

No easy way to fix it after the fact, are you comfortable running an SQL query on your database? This is the one: https://github.com/alucryd/oxyromon/blob/develop/migrations/20241117210150_make_romfile_paths_relative.sql

`ROM_DIRECTORY` must be changed to point to the old path again before running it.

**Comment by vickyorlo** [comment]
Ah, I see. Chalk this up to user error, then, this feels obvious in retrospect. 
I ran the SQL query and fixed the path, and everything seems to work fine now. I added a few rips and did a few light checks and it seems everything works OK now. I'll keep you posted if I see any issues.

**Comment by alucryd** [comment]
0.20.0 just released with the feature included :)
