### ISSUE TITLE
Fails to install via `cargo install oxyromon`

### ISSUE THREAD

**Issue by TheRealGusBus** [alucryd/oxyromon#42]
Output from `cargo install oxyromon`:

> $ cargo install oxyromon
    Updating crates.io index
  Installing oxyromon v0.11.1
   Compiling version_check v0.9.4
   Compiling libc v0.2.126
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.40
   Compiling unicode-ident v1.0.2
   Compiling quote v1.0.20
   Compiling syn v1.0.98
   Compiling cfg-if v1.0.0
   Compiling typenum v1.15.0
   Compiling futures-core v0.3.21
   Compiling cc v1.0.73
   Compiling pkg-config v0.3.25
   Compiling memchr v2.5.0
   Compiling serde v1.0.140
   Compiling once_cell v1.13.0
   Compiling log v0.4.17
   Compiling serde_derive v1.0.140
   Compiling crossbeam-utils v0.8.11
   Compiling pin-project-lite v0.2.9
   Compiling signal-hook v0.3.14
   Compiling proc-macro-hack v0.5.19
   Compiling getrandom v0.1.16
   Compiling futures-io v0.3.21
   Compiling fastrand v1.8.0
   Compiling event-listener v2.5.2
   Compiling cache-padded v1.2.0
   Compiling openssl v0.10.41
   Compiling scopeguard v1.1.0
   Compiling waker-fn v1.1.0
   Compiling futures-task v0.3.21
   Compiling parking v2.0.0
   Compiling native-tls v0.2.10
   Compiling tinyvec_macros v0.1.0
   Compiling percent-encoding v2.1.0
   Compiling futures-channel v0.3.21
   Compiling opaque-debug v0.3.0
   Compiling bitflags v1.3.2
   Compiling subtle v2.4.1
   Compiling parking_lot_core v0.8.5
   Compiling crc32fast v1.3.2
   Compiling async-task v4.3.0
   Compiling cpufeatures v0.2.2
   Compiling matches v0.1.9
   Compiling pin-utils v0.1.0
   Compiling ppv-lite86 v0.2.16
   Compiling crossbeam-queue v0.3.6
   Compiling atomic-waker v1.0.0
   Compiling unicode-bidi v0.3.8
   Compiling serde_json v1.0.82
   Compiling ryu v1.0.10
   Compiling siphasher v0.3.10
   Compiling vcpkg v0.2.15
   Compiling foreign-types-shared v0.1.1
   Compiling smallvec v1.9.0
   Compiling futures-sink v0.3.21
   Compiling futures-util v0.3.21
   Compiling hashbrown v0.12.3
   Compiling const_fn v0.4.9
   Compiling cpuid-bool v0.2.0
   Compiling itoa v1.0.2
   Compiling openssl-probe v0.1.5
   Compiling lexical-core v0.7.6
   Compiling lazy_static v1.4.0
   Compiling arrayvec v0.5.2
   Compiling anyhow v1.0.58
   Compiling static_assertions v1.1.0
   Compiling rle-decode-fast v1.0.3
   Compiling minimal-lexical v0.2.1
   Compiling parking_lot_core v0.9.3
   Compiling rayon-core v1.9.3
   Compiling base64 v0.13.0
   Compiling async-trait v0.1.56
   Compiling http-types v2.12.0
   Compiling httparse v1.7.1
   Compiling adler32 v1.2.0
   Compiling crc-catalog v1.1.1
   Compiling unicode_categories v0.1.1
   Compiling regex-syntax v0.6.27
   Compiling infer v0.2.3
   Compiling same-file v1.0.6
   Compiling paste v1.0.7
   Compiling unicode-width v0.1.9
   Compiling unicode-segmentation v1.9.0
   Compiling hex v0.4.3
   Compiling adler v1.0.2
   Compiling bytes v1.2.0
   Compiling byteorder v1.4.3
   Compiling mime v0.3.16
   Compiling dotenv v0.15.0
   Compiling os_str_bytes v6.2.0
   Compiling remove_dir_all v0.5.3
   Compiling textwrap v0.15.0
   Compiling number_prefix v0.4.0
   Compiling zeroize v1.5.7
   Compiling termcolor v1.1.3
   Compiling oxyromon v0.11.1
   Compiling strsim v0.10.0
   Compiling vec-drain-where v1.0.1
   Compiling simple-error v0.2.3
   Compiling generic-array v0.14.5
   Compiling value-bag v1.0.0-alpha.9
   Compiling ahash v0.7.6
   Compiling standback v0.2.17
   Compiling unicase v2.6.0
   Compiling time v0.2.27
   Compiling cookie v0.14.4
   Compiling nom v5.1.2
   Compiling slab v0.4.7
   Compiling lock_api v0.4.7
   Compiling num-traits v0.2.15
   Compiling memoffset v0.6.5
   Compiling indexmap v1.9.1
   Compiling crossbeam-epoch v0.9.10
   Compiling tokio v1.20.0
   Compiling rayon v1.5.3
   Compiling instant v0.1.12
   Compiling cmake v0.1.48
   Compiling openssl-sys v0.9.75
   Compiling md5-asm v0.5.0
   Compiling sha1-asm v0.5.1
   Compiling concurrent-queue v1.2.2
   Compiling async-lock v2.5.0
   Compiling simple-mutex v1.1.5
   Compiling tinyvec v1.6.0
   Compiling form_urlencoded v1.0.1
   Compiling phf_shared v0.8.0
   Compiling phf_shared v0.10.0
   Compiling foreign-types v0.3.2
   Compiling libsqlite3-sys v0.24.2
   Compiling libflate_lz77 v1.1.0
   Compiling crc v2.1.0
   Compiling walkdir v2.3.2
   Compiling heck v0.4.0
   Compiling miniz_oxide v0.5.3
   Compiling clap_lex v0.2.4
error: failed to run custom build command for `oxyromon v0.11.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installxikUHb/release/build/oxyromon-04745c1bcf909968/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'failed to delete .svelte-kit: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/gus/.cargo/registry/src/github.com-1ecc6299db9ec823/oxyromon-0.11.1/build.rs:17:43
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `oxyromon v0.11.1`, intermediate artifacts can be found at `/tmp/cargo-installxikUHb`

**Comment by alucryd** [comment]
Do you have `yarn` in your PATH? It should be invoked by the build process to build the frontend, if `.svelte-kit` doesn't exist it means something went wrong during the frontend build. That said I never actually tried cargo install, always built from the source folder so I'll look into it.

**Comment by alucryd** [comment]
Should be fixed in https://github.com/alucryd/oxyromon/commit/0f796fa6b5f26376edf32f3efbabdec3eb32cdbc

It will only require yarn when the server feature is active from now on, will be included in the next release.

**Comment by alucryd** [comment]
New release is up, I am able to `cargo install` it. Please let me know if that doesn't work for you.

**Comment by TheRealGusBus** [comment]
Installs now. Thanks
