### ISSUE TITLE
import-roms panics

### ISSUE THREAD

**Issue by TheRealGusBus** [alucryd/oxyromon#43]
Removing the short option fixes it, but I don't know if this has any unwanted side effects elsewhere.

> thread 'main' panicked at '`help`s `-h` conflicts with `HASH`.
>
> To change `help`s short, call `cmd.arg(Arg::new("help")...)`.', /home/gus/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.18/src/build/command.rs:4484:25

**Comment by alucryd** [comment]
Sorry, I fixed it in the 0.11 branch and released a 0.11.1 afterwards, but I never merged the fix in master. Just did it, thanks for the heads up.
