### ISSUE TITLE
sort-roms -m/--missing not implemented

### ISSUE THREAD

**Issue by aarongeorge** [alucryd/oxyromon#51]
The documentation references the -m/--missing flags for sort-roms however it doesn't seem to be implemented

**Comment by alucryd** [comment]
Must have forgot to update the doc, it's `--wanted`. Will update asap.

**Comment by alucryd** [comment]
Fixed in https://github.com/alucryd/oxyromon/commit/dd005d8a158b88fab2f20fd73d1ed02da560a347 :)
