### ISSUE TITLE
1G1R problems?

### ISSUE THREAD

**Issue by aarongeorge** [alucryd/oxyromon#52]
Any chance we could get a 1G1R generator that is similar to https://github.com/andrebrait/DATROMTool?

At the moment I'm having a hard time working out how to use this "hybrid" mode for sort-roms to give me preferences of a few regions per title but falling back to any region if it doesn't exist.

E.g. If I have preference for EUR,US then if I hit a JAP game that exists only in JAP I would like that included in the 1G1R output, but can't get that to happen currently.

Any ideas? Thanks!

**Comment by alucryd** [comment]
Why not use EUR,USA,JAP for 1G1R? Sounds like that would achieve what you want.

**Comment by aarongeorge** [comment]
Fair, it just means I have to make sure to include all of the regions when generating the 1G1R in order of priority (Where DATROMTool handles omitted regions).

I'll do this for now though, thanks. So far using this has been great!

**Comment by aarongeorge** [comment]
I ran it with all of the regions in order and that works. There was a few inconsistencies when compared to the above mentioned tool, but I think that's because it looks at the actual languages and not just the regions.

Thanks mate
