### ISSUE TITLE
[FEATURE] 1G1R Sub-Folders

### ISSUE THREAD

**Issue by aarongeorge** [alucryd/oxyromon#53]
Systems like the Analogue hardware choke when too many ROMs are present in a single directory. The work around it putting ROMs inside of a Letter directory. For example `Test Game.rom` would exist in a `T` directory inside the 1G1R.

Is this something that could be considered for `sort-roms`?

**Comment by alucryd** [comment]
Sounds easy enough, I can gate that behind a cli flag and/or a config option, will have a look over the weekend.

**Comment by aarongeorge** [comment]
Great! Thanks mate! I'm slowly working my way through the Rust book so should be able to actually submit merge requests instead of asking for things

**Comment by aarongeorge** [comment]
Just built and tested it. That's great! Thank you!
