### ISSUE TITLE
[Feature] Keep system sub-sets in separate directories

### ISSUE THREAD

**Issue by TheRealGusBus** [alucryd/oxyromon#54]
As an example, Oxyromon will place these three separate sets in the "Sony - Playstation 3" directory:

- "Sony - Playstation 3"
- "Sony - Playstation 3 (PSN) (Content)"
- "Sony - Playstation 3 (PSN) (Updates)"

**Comment by alucryd** [comment]
Made it like that because I found that dat-o-matic's naming was very much inconsistent and regularly changed quite a bit, in the daily package they would even duplicate `(Parent-Clone)` sometimes.

Initially I would only remove `(Parent-Clone)` from the DAT name if it exists, I can add an option to do that again, but beware that you might have to fix some DAT files manually.

**Comment by TheRealGusBus** [comment]
I think in this specific case it might be fine. Is the Parent-Clone issue only with the arcade DATs?

**Comment by alucryd** [comment]
That was happening on console DATs from Dat-o-matic, those that had duplicate `(Parent-Clone)` had one in the system name inside the DAT (while those that had only one in the filename had none in the system name). Most likely a bug at the time, and it seems to have been fixed as I don't sse any issue in the latest daily archive.

In any case, it's now implemented in https://github.com/alucryd/oxyromon/commit/183da79cab69b5596c17e8938fd27922e0da5d83

Created a new boolean config entry, `GROUP_SUBSYSTEMS`. Defaults to true so it stays consistent with existing installations, you can set it to false (`oxyromon config -s GROUP_SUBSYSTEMS false`) and `sort-roms` should fix your existing paths. Additionally `import-roms` should also take it into account.

Please let me know how that goes.

**Comment by TylerVigario** [comment]
I'd like to note that N64 `Big-Endian` isn't filtered out.

[Screenshot](https://i.imgur.com/647tQlj.png)

**Comment by TheRealGusBus** [comment]
Sorry for the long delay. it seems to working well so far.

**Comment by alucryd** [comment]
Awesome, thanks for the feedback!
