### ISSUE TITLE
[FEATURE] REGIONS_ALL keyword to include all regions

### ISSUE THREAD

**Issue by aarongeorge** [alucryd/oxyromon#55]
It would be great if there was a keyword we could use in REGIONS_ALL (perhaps ALL) to include all regions as a quick way to "unsure" the roms.

**Comment by alucryd** [comment]
The current logic uses the Region enum from shiratsu-naming, it doesn't have a catch-all region per se, and adding an `ALL` choice is a bit more involved that I'd like.

However there is an `Unknown` entry in the enum, that would be mapped to `ZZ` as far as REGIONS_ALL is concerned. Not sure how common these are in romsets, but it seems like a good compromise for a catch-all region. What do you think?

**Comment by alucryd** [comment]
Did just that: https://github.com/alucryd/oxyromon/commit/bc7ef44502c4c39296ef75073de27d2ded6a8615

Note that it only applies to 1G1R/hybrid mode, as in normal mode you can already keep everything if you leave both `REGIONS_` lists blank.

**Comment by aarongeorge** [comment]
Thanks mate. Hmm, I'll have a play around with it. Maybe I should hit up shiratsu-naming about an all case.

I only mention this because I am using the config as my most common sorting, but wanted to be able to quickly run different commands to revert back to an unsorted version
