### ISSUE TITLE
[Feature] m3u support

### ISSUE THREAD

**Issue by TylerVigario** [alucryd/oxyromon#56]
Can we add support for .m3u files for multi-disc games? I created .m3u files for my GameCube games but they aren't importing with oxyromon.

**Comment by alucryd** [comment]
Yeah, that's on my to-do list, the plan even if to auto detect multi disc games and create m3u files automatically. Can't give you an ETA though, but it's definitely planned.

**Comment by TylerVigario** [comment]
Thanks, I see that now in the README. Sorry I missed it but thanks for the awesome project!

**Comment by alucryd** [comment]
@TylerVigario Guess what? https://github.com/alucryd/oxyromon/commit/eefb923817c9a5af98bc5aed564a5335ad2b2d43 ;)

Will work with Redump DATs that use the `(Disc n)` convention. M3U files should follow their rom if they are moved by `sort-roms` (haven't tried it yet), but you'll need to generate them again if you use `convert-roms` to change their format.

Note that the first time you call this new version it will probably seem unresponsive if you already have an extensive library. This is adding a new indexed field in the database, and indexation can take some time.

**Comment by TylerVigario** [comment]
This is great news! I am completing my GC & Wii (RVZ) games conversion and will test and report back if any issues arise with M3U creation.
