### ISSUE TITLE
[Issue] Unable to import MAME dat

### ISSUE THREAD

**Issue by TylerVigario** [alucryd/oxyromon#58]
Having trouble importing a MAME dat from www.progettosnaps.net

`oxyromon import-dats -a "MAME 0.250.dat"`

```
Processing ""MAME 0.250.dat""
Error: SimpleError { err: "Failed to parse DAT file, missing field `game`" }
```

**Comment by alucryd** [comment]
Looks like they don't respect the Logiqx format, which is unfortunate, all `game` tags are replaced with `machine` tags. Will see if I can use one or the other without having to write an ugly hack :/

**Comment by alucryd** [comment]
Managed to do it cleanly in https://github.com/alucryd/oxyromon/commit/f39cc6150a2973e28c175b991016e42042d422b0 :)

**Comment by TylerVigario** [comment]
Worked great!

**Comment by TylerVigario** [comment]
Waiting on #59 to import my Arcade collection but have noticed that Oxyromon will mark games as `Complete` despite [having no ROMs](https://i.imgur.com/QUh2lWI.png) or all [ROMs are missing](https://i.imgur.com/0velH1c.png).
