### ISSUE TITLE
[Issue] Arcade DATs missing ROMs

### ISSUE THREAD

**Issue by TylerVigario** [alucryd/oxyromon#65]
Waiting on https://github.com/alucryd/oxyromon/issues/59 to import my Arcade collection but have noticed that Oxyromon will mark releases as `Complete` when there [are no ROMs](https://i.imgur.com/QUh2lWI.png) or all [ROMs failed to import](https://i.imgur.com/0velH1c.png).

**Comment by alucryd** [comment]
That's unfortunately not the only issue xD I also see complete games that are not marked complete here. Wonder at which point I broke it so bad. Been a while since I last touched my MiSTeR so I had put arcade on the backburner.

**Comment by alucryd** [comment]
We should be in a much better place now regarding arcade, at least I don't see any obvious inconsistency in the web UI in the develop branch. Should publish a new release soon :)
