### ISSUE TITLE
Mega Man Legends (USA) doesn't verify

### ISSUE THREAD

**Issue by isavegas** [alucryd/oxyromon#66]
I'm unable to import my dump of `Mega Man Legends (USA)` for PlayStation due to Oxyromon not correctly verifying `Mega Man Legends (USA).cue` or `Mega Man Legends (USA) (Track 1).bin`. Track 2 is correctly imported.

I attempted to update the PlayStation dat via `oxyromon download-dats --redump --update --all --force` and verified my files with the md5 checksums found on [the Redump website](http://redump.org/disc/2773/).

Command used: `oxyromon import-roms -a MD5 "Mega Man Legends (USA).cue"`

I am using Oxyromon 0.13.0 on Linux.

![image](https://user-images.githubusercontent.com/3105000/211960935-9ff16985-e622-4b22-b265-6c0d9671cf93.png)

**Comment by alucryd** [comment]
Just successfully imported these files using CRC, but I can indeed reproduce with MD5. Looks like a bug with MD5, thanks for reporting, I'll look into it.

**Comment by alucryd** [comment]
Just pushed: https://github.com/alucryd/oxyromon/commit/f3e981c72eaf0067048ac444228f9eaf0d70a1d1

With this, oxyromon will tell you if you have already imported a rom instead of displaying `No match`.

Please let me know if the above steps did the trick for you. Hopefully I can release the next stable with these changes soon.

**Comment by isavegas** [comment]
> Wait, are you sure you haven't imported them yet? Can you confirm in your playstation dir, and try running `oxyromon purge-roms -m -o -t` if you don't see anything then importing again?
> 
> Handling of already imported games is awkward right now, I don't tell you it's already been imported, I just print that there is no match, simply because I only go over games that haven't been imported yet (even though I have db indexes, it's faster that way). Guess I could add a subsequent search among already imported games in case there is no match.
> 
> In any case, dropping the files I imported via CRC, I was able to import them via MD5 (and SHA1 as well).

I did have `Mega Man Legends (USA) (Track 2).bin` that had been imported by a previous bad dump. Removing that and running `oxyromon purge-roms -m -o` allowed me to import the dump using CRC. I had switched to MD5 for tests after starting with a fresh backup, with oxyromon only pulling in track 2, which *then* broke CRC on future attempts.

I appreciate the help!
