### ISSUE TITLE
Catch network errors during download-dat

### ISSUE THREAD

**Issue by TylerVigario** [alucryd/oxyromon#70]
Got an error during updating my Redump DATs today.

```
Processing "Sony - PlayStation 2"
⠠
thread 'main' panicked at 'Failed to download ZIP: connection closed', src/download_dats.rs:270:10
```

**Comment by alucryd** [comment]
I was being lazy here because surf's error does not have the StdError trait, which makes it a pain to handle :P I'll see what I can do.

**Comment by alucryd** [comment]
Done, it will simply progress to the next DAT now :)
