### ISSUE TITLE
"CUE file not found, using single track mode" when using chd images

### ISSUE THREAD

**Issue by anderbubble** [alucryd/oxyromon#75]
It's my understanding that the chd image format replaces both bin/cue files; so when scanning a chd image, why does oxyromon need a cue file?

```
CUE file not found, using single track mode
```

**Comment by TylerVigario** [comment]
Because the DATs we are using don't verify CHD (it's hard to find up-to-date CHD DATs) files. They actually validate against ISO, BIN/CUE, etc. Thus Oxyromon needs to reconstruct the original file from the CHD to validate against the DAT. The reason you need the CUE file is so Oxyromon can understand how to put the original file back together from the CHD.

**Comment by TylerVigario** [comment]
> edit: to be clear, I'm definitely not an expert, so maybe there's something I'm missing; but that's how it seems from what I'm reading.

I totally agree with your position as I had the same understanding. However, I am not an expert either. Hopefully @alucryd will chime in with some specifics as to why `CHD -> X` conversion requires a CUE file.

**Comment by TylerVigario** [comment]
@alucryd Seems like they should have designed a better suited CUE file alternative. Second precision seems to be designed with only audio tracks in mind.

**Comment by anderbubble** [comment]
@alucryd thanks for that explanation. I think I see now: when you have bin/cue, each track is a separate file, so you have bit- (or maybe byte-)level granularity of what data is in what track. But when you extract a chd to bin/cue, as you said, I get one bin and then pointers into that bin from the cue, which only has second-level granularity.

So it it possible to verify a multi-track chd file, if you have the cue? What's the right way to do that? Do I just need to have the right cue placed alongside the chd with the same base name? If oxyromon renames the files, does it update the cue as well?

**Comment by TylerVigario** [comment]
Oxyromon will always base its ROM (and CUE) filename based on the DAT.

**Comment by alucryd** [comment]
The CUE file should have the same name as the CHD and be placed alongside the CHD. You should import the CHD only, the CUE will be picked up automatically. I'll clarify that in the documentation.

Roms are always looked up by both their size and hash, I also try to match the game and/or rom name too, helps when there are a lot of dupes, like for arcade.

**Comment by Immersion95** [comment]
Would it be possible to import the Cue archive from redump with the Dat archive ? Or specify the archive containing the Cue archive ?

verifydump actually use the archive as no one is keeping the cue files alongside chd files.

**Comment by alucryd** [comment]
@Immersion95 I guess I could download them as they're public, but you would need to have your CHD already renamed to match the Redump name as I have no way of linking the CHD to the CUE otherwise :/

**Comment by Immersion95** [comment]
> @Immersion95 I guess I could download them as they're public, but you would need to have your CHD already renamed to match the Redump name as I have no way of linking the CHD to the CUE otherwise :/

Yes of course

**Comment by alucryd** [comment]
I'll add it to the todo list.

Note that the smart import won't work here either, I will need to prompt for the system, fortunately I already have a map of system name and codes [here](https://github.com/alucryd/oxyromon/blob/bb3bbae6cd326c25def0386f26ad1778c3a17665/src/download_dats.rs#L33). I may be able to circumvent the need to have the correct name if I prompt for the game as well (similarly to what I'm doing with PS3/IRD files already) using a distance lookup between the CHD name and CUE names.
