### ISSUE TITLE
Set ROM_DIRECTORY on Windows error

### ISSUE THREAD

**Issue by Zombanana** [alucryd/oxyromon#92]
Hi,

I don't know if I am just to stupid to set the ROM_DIRECTORY or if it's a bug.
I am on Windows 11.

Setting the "ROM_DIRECTORY" with following command:
oxyromon config -s ROM_DIRECTORY D:\Redump

results in

Creating "\\\\?\\D:\\Redump"

![1](https://github.com/alucryd/oxyromon/assets/97361360/11db6431-0d7c-43d7-9ac5-3af7fbf41f68)
![2](https://github.com/alucryd/oxyromon/assets/97361360/4a6d89d9-0a7f-4c3c-a794-081b0bd8801d)

Is this a bug or I am to stupid?
Sorry if this is my stupidness :/

**Comment by Zombanana** [comment]
The ROM_DIRECTORY Path works as expected, it seems to be just a display error.
If you start the webserver and edit the path inside this, it shows the ROM_DIRECTORY Path also correctly.
The Display Error is just listed from cmd.

My fault was that I thought oxyromon, would find my Roms immediatly, after I set the Rom Directory Path.
But you still have to use the "import-roms" command.

After that everything went fine.

**Comment by alucryd** [comment]
Thanks for bringing this to my attention, will need to find why it displays wrong on Windows, shouldn't be too hard to fix.

**Comment by alucryd** [comment]
Hopefully this fixes the paths on Windows: https://github.com/alucryd/oxyromon/commit/ca24983a9afe4d84d9b44bab710244863ea300b1

Don't have a Windows install to test right now, will probably create a VM.

**Comment by Zombanana** [comment]
Hi,

after 0.17.0 is released, I can test it. I have Windows installed on my machine and report it back to you.
By the way, the issue is just visual.

**Comment by alucryd** [comment]
@Zombanana Released 0.17.0 in november, did you have time to test it?

**Comment by Zombanana** [comment]
Hi alucryd,

Unfortunately I am right now in the process of building a new Unraid Server and to move all my drives / data from Windows to an Unraid array. At the moment I have no access to my data until it's moved to the Unraid server.

So that can take a while until I am ready :/

**Comment by alucryd** [comment]
No worries, please take your time.

**Comment by alucryd** [comment]
Going to close as I'm fairly sure the commit I linked above did fix the issue. Please reopen if that's not the case.
