### ISSUE TITLE
[Feature I think?] Don't create folders for systems without roms. 

### ISSUE THREAD

**Issue by monyarm** [alucryd/oxyromon#93]
I just used download-dats to grab the disc and cartridge dats I need. However, I don't have dumps for all of them (for some I'm waiting on the necessary device to dump them, for others, I've just grabbed the dats, even though I don't own any games for that system yet.)
One thing that bothers me, is that oxyromon has created a bunch of folders for systems without any roms, just empty folders, with empty trash folders in them.
I think that having oxyromon clean such folders (not create them, and delete them if they exist), and only create them when importing roms.

Now it's a minor issue, cause I can just use `find . -empty -type d -delete` to recursively delete empty folders, so having oxyromon handled things (in what I think would be) a better way, isn't strictly necessary. Still felt I should mention it.

**Comment by alucryd** [comment]
Will look into it, as long as I check for missing folders and create them on demand in other parts of the code, skipping empty dir creation will be fine.

**Comment by alucryd** [comment]
It's now in the latest release :)
