### ISSUE TITLE
[Feature]: Delete temp/cache file immediately

### ISSUE THREAD

**Issue by Zombanana** [alucryd/oxyromon#95]
Hi,

I have large Rom Sets, which I started to convert with oxyromon.
I have define my temp folder to use a big Hard Drive during the conversion process.

The problem is that my sets are that large, that I have to delete some files of the temp folder manually during the conversion before it crashes or I wait until it crashes because I run out of space and start the conversion from new to convert the rest of Roms.

It would be nice, if oxyromon would delete the Rom immediately after converting it and not after the complete job is done.
This would avoid a crash.

Also it would open the option to create a RAM-Disk and point the temp folder to it.
That would speed up the complete conversion process.

Edit: Right now I am converting my Roms into .chd.
I am not sure if that is a problem because oxyromon uses chdman.exe.

**Comment by alucryd** [comment]
This is what is supposed to be done already, but I may have missed one deletion indeed. What format are you converting from?

**Comment by Zombanana** [comment]
Hi,

I have converted my sets from zip(ed) bin/cue and zip(ed) iso files.
Some of my "Redump - Sony PlayStation" and "Redump - Sony PlayStation 2" Roms.

It deletes the temp files, when everything is converted.
But it can take some hours and I allways run into crash, because of missing space.
Better it would delete every single file after conversion.

Thanks into watching this.

BTW: I haven't tested it with CSO for now.

**Comment by alucryd** [comment]
Thanks for the kind words :)

Should be fixed in https://github.com/alucryd/oxyromon/commit/4702faf9028c8023b46cd48366b3550a795e0384

I actually moved the temp dir creation down in scope so it is always deleted between each file when it goes out of scope, since this is not something I can catch in a unit test, this is less error-prone than deleting temp files manually.

**Comment by alucryd** [comment]
@Zombanana Finally got around to releasing the fix. It has been a crazy summer, thankfully I should have way more time to work on this in autumn and winter.
