### ISSUE TITLE
Exit on processing a zip file with folder inside

### ISSUE THREAD

**Issue by bhartshorn** [alucryd/oxyromon#98]
Hi, one more here, this is not actually a rom but the patcher for the fan translation of Mother 3, anyway, it contains a folder inside which is making oxyromon choke. Seems like a better experience to just give up on this file and move on rather than exiting.

```
Processing "MOTHER3_EarthBound2_English_v1.3.zip"
Processing "MOTHER3_EarthBound2_English_v1.3 (MOTHER3_EarthBound2_English_v1.3.zip)"
Extracting "MOTHER3_EarthBound2_English_v1.3"
Error: SimpleError { err: "Failed to copy data, Is a directory (os error 21)" }
```

**Comment by alucryd** [comment]
I should probably traverse folders inside archives at some point, but ignoring them should be an easy temporary solution to the problem.

**Comment by alucryd** [comment]
Looks like I fixed this as part of the big refacto :)
